### ISSUE TITLE
Fix logout bug

### ISSUE THREAD

**Issue by tanyjnaaman** [CS3219-AY2223S1/cs3219-project-ay2223s1-g47#75]

**Comment by cookiedan42** [comment]
browser is keeping copy of jwt
seems like logout overwrite isn't working

**Comment by cookiedan42** [comment]
![image](https://user-images.githubusercontent.com/42330243/197970580-1baf4492-fbe7-468a-a516-0a828d478ea2.png)
Further narrowing down, these two calls to auth after logout have the old valid cached JWT stuck to them
